// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTemphighChange();
void onTemplowChange();
void onServoSwChange();

CloudTemperatureSensor temp;
int temphigh;
int templow;
bool servo_sw;
bool situation;

void initProperties(){

  ArduinoCloud.addProperty(temp, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temphigh, READWRITE, ON_CHANGE, onTemphighChange, 40);
  ArduinoCloud.addProperty(templow, READWRITE, ON_CHANGE, onTemplowChange, 10);
  ArduinoCloud.addProperty(servo_sw, READWRITE, ON_CHANGE, onServoSwChange);
  ArduinoCloud.addProperty(situation, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
